package ro.ase.eu.proiect.database;

public interface DatabaseConstants {
    String DATABASE_NAME="buswaybucharest.db";
    int DATABASE_VERSION=1;

    String TABLE_NAME_LINE = "Line";
    String COLUMN_LINE_ID="_id";
    String COLUMN_LINE_GLOBALID = "globalId";
    String COLUMN_LINE_NUMBER="number";
    String COLUMN_LINE_STARTINGPOINT="startingPoint" ;
    String COLUMN_LINE_ENDINGPOINT="endingPoint";


    String TABLE_NAME_ROUTESTOP = "RouteStop";
    String COLUMN_ROUTESTOP_LINEID="lineId";
    String COLUMN_ROUTESTOP_STOPID="stopId";

    String TABLE_NAME_STOP = "Stop";
    String COLUMN_STOP_ID="_id";
    String COLUMN_STOP_NAME="name";
    String COLUMN_STOP_LATITUDE="latitude" ;
    String COLUMN_STOP_LONGITUDE="longitude";

    String TABLE_NAME_FAVORITELINE = "FavoriteLine";
    String COLUMN_FAVORITELINE_ID="lineId";

    String CREATE_TABLE_LINE = "CREATE TABLE "+TABLE_NAME_LINE + " (" + COLUMN_LINE_ID + " INTEGER PRIMARY KEY AUTOINCREMENT, "+
            COLUMN_LINE_GLOBALID + " TEXT, "+
            COLUMN_LINE_NUMBER  + " TEXT, " + COLUMN_LINE_STARTINGPOINT + " TEXT, "+ COLUMN_LINE_ENDINGPOINT + " TEXT )";
    String DROP_TABLE_LINE = "DROP TABLE IF EXISTS "+ TABLE_NAME_LINE;

    String CREATE_TABLE_ROUTESTOP = "CREATE TABLE "+TABLE_NAME_ROUTESTOP + " ( " + COLUMN_ROUTESTOP_LINEID+ " INTEGER NOT NULL, "+
            COLUMN_ROUTESTOP_STOPID  + " INTEGER NOT NULL, PRIMARY KEY (" +COLUMN_ROUTESTOP_LINEID +", "+ COLUMN_ROUTESTOP_STOPID +"), FOREIGN KEY ("+ COLUMN_ROUTESTOP_STOPID + ") REFERENCES "+
            TABLE_NAME_STOP+ " ("+COLUMN_STOP_ID+"), FOREIGN KEY ("+  COLUMN_ROUTESTOP_LINEID +") REFERENCES " + TABLE_NAME_LINE +"( " + COLUMN_LINE_ID +
            ") ON DELETE CASCADE ON UPDATE NO ACTION)";
    String DROP_TABLE_ROUTESTOP = "DROP TABLE IF EXISTS "+ TABLE_NAME_ROUTESTOP;



    String CREATE_TABLE_STOP = "CREATE TABLE "+TABLE_NAME_STOP + " (" + COLUMN_STOP_ID+ " INTEGER PRIMARY KEY AUTOINCREMENT, "+
            COLUMN_STOP_NAME  + " TEXT, " + COLUMN_STOP_LATITUDE + " TEXT, "+ COLUMN_STOP_LONGITUDE + " TEXT);";
    String DROP_TABLE_STOP = "DROP TABLE IF EXISTS "+ TABLE_NAME_STOP;

    String CREATE_TABLE_FAVORITELINE = "CREATE TABLE "+TABLE_NAME_FAVORITELINE+ " (" + COLUMN_FAVORITELINE_ID + " INTEGER NOT NULL, FOREIGN KEY ("+ COLUMN_FAVORITELINE_ID + ") REFERENCES "+
            TABLE_NAME_LINE+ " ("+COLUMN_LINE_ID+") ON DELETE CASCADE ON UPDATE NO ACTION )";
    String DROP_TABLE_FAVORITELINE = "DROP TABLE IF EXISTS "+ TABLE_NAME_FAVORITELINE;

    String JOIN_TABLES_FAVORITELINE_LINE = "SELECT * FROM " + TABLE_NAME_LINE + " t1 INNER JOIN " + TABLE_NAME_FAVORITELINE +
            " t2 ON t1." + COLUMN_LINE_ID +" = t2." + COLUMN_FAVORITELINE_ID + " GROUP BY t1." + COLUMN_LINE_ID;
    String LEFT_JOIN_TABLES_LINE_FAVORITELINE = "SELECT * FROM " + TABLE_NAME_LINE + " t1 LEFT JOIN " + TABLE_NAME_FAVORITELINE +
            " t2 ON t1." + COLUMN_LINE_ID +" = t2." + COLUMN_FAVORITELINE_ID + " GROUP BY t1." + COLUMN_LINE_ID;
}
